<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-SI6BME8H" failures="1" tests="1" name="Tests.TestRunner" time="48.066" errors="0" timestamp="2023-09-15T20:43:01 IST" skipped="0">
  <testcase classname="Tests.TestRunner" name="runScenario" time="48.066">
    <failure message="expected:&lt;Success&gt; but was:&lt;Successaa&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<Success> but was:<Successaa>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at Tests.StepDefinition.he_should_should_verify(StepDefinition.java:72)
at âœ½.he should should verify- "Success"(file:///C:/Users/chirr/eclipse-workspace/RLLCucumber/Features/user.registration1.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Tests.TestRunner -->
