<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-SI6BME8H" failures="1" tests="1" name="Default test" time="48.716" errors="0" timestamp="2023-09-15T20:43:01 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="48.066">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Success&amp;gt; but was:&amp;lt;Successaa&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Success> but was:<Successaa>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at Tests.StepDefinition.he_should_should_verify(StepDefinition.java:72)
at âœ½.he should should verify- "Success"(file:///C:/Users/chirr/eclipse-workspace/RLLCucumber/Features/user.registration1.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
